services:
  - type: web
    name: chat-app
    env: node
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: node src/index.js
    buildFilter:
      paths:
        - frontend/**
        - backend/**
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
